name: rainweather_flutter
description: "知雨天气2 - 智能天气预报应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # HTTP Requests
  http: ^1.2.2
  dio: ^5.7.0
  
  # Location Services
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  
  # Local Storage
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.2
  
  # Charts
  fl_chart: ^1.1.1
  
  # Image Loading
  cached_network_image: ^3.4.1
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # Date/Time
  intl: ^0.20.2
  
  # Background Tasks
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  
  # UI Enhancements
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  
  # Path utilities
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgroud.png
    - assets/images/splash.jpg
    - assets/icons/
    - assets/cities.json
    - assets/data/
